### ISSUE TITLE
[Finance] Figure out how to create file download links on google sites so that people can download our 2021 finance report

### ISSUE THREAD

**Issue by kbonnen** [NeuromatchAcademy/NeuromatchAcademy.github.io#14]

**Comment by maryiii** [comment]
We need to upload our file on google drive and share the link/embed the google drive file in our webpage as follows:
https://www.youtube.com/watch?v=SlntM9RNSj8

**Comment by kbonnen** [comment]
@maryiii This is the higher priority task (between the two you've commented on)

**Comment by maryiii** [comment]
@kbonnen I've figured out how to do this! Do we have the file already? Where can I find it?
